### ISSUE TITLE
Unable to add tap - Invalid formula: /opt/homebrew/Library/Taps/aws/homebrew-tap/Formula/eks-anywhere.rb

### ISSUE THREAD

**Issue by xobed** [aws/homebrew-tap#228] opened 2021-09-09 08:58 UTC
OS X Big Sur 11.5.2
Apple M1

➜ brew --version
Homebrew 3.2.11
Homebrew/homebrew-core (git revision 4f77196f8a; last commit 2021-09-09)
Homebrew/homebrew-cask (git revision 7edff39a8e; last commit 2021-09-09)

➜ brew tap aws/tap
==> Tapping aws/tap
Cloning into '/opt/homebrew/Library/Taps/aws/homebrew-tap'...
remote: Enumerating objects: 2222, done.
remote: Counting objects: 100% (985/985), done.
remote: Compressing objects: 100% (631/631), done.
remote: Total 2222 (delta 817), reused 450 (delta 353), pack-reused 1237
Receiving objects: 100% (2222/2222), 355.74 KiB | 110.00 KiB/s, done.
Resolving deltas: 100% (1478/1478), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/aws/homebrew-tap/Formula/eks-anywhere.rb
formulae require at least a URL
Error: Cannot tap aws/tap: invalid syntax in tap!

**Comment by toricls** [comment] 2021-09-09 09:21
@xobed It doesn't support Arm based processors today. Thus there is no binary published for `darwin/arm64` and this is the reason of the error.

https://anywhere.eks.amazonaws.com/docs/getting-started/install/
> EKS Anywhere only works on computers with x86 and amd64 process architecture. It currently will not work on computers with Apple Silicon or Arm based processors.

**Comment by xobed** [comment] 2021-09-09 09:27
I actually want to install SAM CLI
https://aws.amazon.com/serverless/sam/

But this formula error prevents me from adding the tap

**Comment by zhanglongyang** [comment] 2021-09-09 11:55
Was trying to `brew install aws-sam-cli-beta-cdk` and encountered the same issue on apple M1, end up cloning this repo and installing it from local file as a workaround.
```
brew install --build-from-source ./Formula/aws-sam-cli-beta-cdk.rb
```

**Comment by toricls** [comment] 2021-09-09 13:32
@rothgar Can you take a look into this? I think the cause of this issue could be the `eks-anywhere` formula.

**Comment by eddiezane** [comment] 2021-09-09 18:01
This should be fixed! Apologies for the inconvenience.

**Closed** 2021-09-09 18:00 UTC
