### ISSUE TITLE
sam CLI installation not working with homebrew 2.4.16

### ISSUE THREAD

**Issue by daria-hyuna** [aws/homebrew-tap#132] opened 2020-09-01 14:14 UTC
After the update to homebrew 2.4.16 aws sam cli is no longer being installed correctly using homebrew
**Reproduction Steps**
My installation steps of aws cli and sam cli are as follows
```
    - echo "Installing AWS CLI V1"
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    - aws --version
    - echo "Installing SAM"
    - bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    - test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
    - echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
    - brew --version
    - brew tap aws/tap
    - brew install aws-sam-cli
    - sam --version
```
**Expected behavior**
`sam --version` should have the output ` SAM CLI, version 1.0.0`

**What happened**
`sam --version` had the following output 
``` 
Command 'sam' not found, but there are 18 similar ones.
The command "sam --version" failed and exited with 127 during .
 ```

**Environment**
- Homebrew version 2.4.16
- aws-cli version 1.18.129
- Node.js Version: v12.16.3
- OS: linux
- Dist: bionic

**Other**
The only difference I have found between my old successful build and the current failed is the homebrew version from 2.4.14 to 2.4.16

**Comment by DanielFrank** [comment] 2020-09-02 16:12
There's a possible workaround [here](https://github.com/CircleCI-Public/aws-sam-serverless-orb/issues/20#issuecomment-685069901) (Basically the problem seems to be that the reinstall isn't soft-linking `sam` in the brew bin folder)

**Comment by hoffa** [comment] 2022-01-03 02:54
Unable to reproduce in https://github.com/aws/homebrew-tap/issues/189#issuecomment-1003839775; closing.

**Closed by hoffa** 2022-01-03 02:54 UTC
